train_file: ['video_dataset/cc3m/txt/cc3m.json',
             ] # local path to image data CC3M
laion_path: ''

args: {
    dataset_name: WebVid,
    data_dir: video_dataset/WebVid, #local path to video data webvid
    shuffle: true,
    num_workers: 0,
    batch_size: 8,
    
    split: train,
    cut: 2M,
    subsample: 1,
    text_params: {
        input: text
    },
    video_params: {
        input_res: 256,
        num_frames: 4,
        loading: lax,
        frame_sample: headtail
    },
}
# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
use_subset: 0
image_size: 256
batch_size: 30

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 3e-4
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 40
warmup_steps: 3000

visual_model_cfg: configs/timesformer_divst_8x32_224_k600.json

